# Define recurring tasks here. See:
# https://guides.rubyonrails.org/active_job_basics.html#recurring-tasks
#
# Example:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
